# Generated by Django 3.2.19 on 2023-07-13 22:08
from django.db import connection
from django.db import migrations, models
from django.conf import settings
import json


class Migration(migrations.Migration):
    
    initial = True

    dependencies = [
        ("models", "9945_file_thumbnail_bin_file_thumbnail_text"),
    ]

    def forward(apps, schema_editor):
        source_details = json.dumps({'type': 'vector', 'tiles': [f'{settings.PUBLIC_SERVER_ADDRESS}application-areas/{{z}}/{{x}}/{{y}}.pbf'], 'minzoom': 6, "data": "/geojson?nodeid=1909956f-3a3b-11eb-ae99-f875a44e0e11"})
        with connection.cursor() as cursor:
            sql = f"""
                update map_sources 
                set source = %s
                where name = 'select-application-area';
                delete from map_sources where name in ('select-area', 'select-monument');
            """
            cursor.execute(sql, [source_details])

    def backward(apps, schema_editor):
        with connection.cursor() as cursor:
            sql = """
                update map_sources 
                set source = '{"data": "/geojson?nodeid=1909956f-3a3b-11eb-ae99-f875a44e0e11&include_geojson_link=true", "type": "geojson!"}' 
                where name = 'select-application-area';
                delete from map_sources where name in ('select-area', 'select-monument');
            """
            cursor.execute(sql)

    operations = [
        migrations.RunPython(forward, backward),
    ]
